name: unsplash_api
description: An unsplash API library for Dart language
version: 0.6.3-alpha
repository: https://github.com/innerwilds/unsplash_dart_api.git

environment:
  sdk: ^3.5.1

dependencies:
  collection: ^1.18.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
